### ISSUE TITLE
create a way for organizers to email all volunteers in a project at once (or is there a way?)

### ISSUE THREAD

**Issue by farmernate** [ExperimentalFarmNetwork/efn-drupal#110] opened 2018-01-30 04:06 UTC
Admins: can send emails to all users
Project creators: can send emails to their volunteers via project page

Currently, as far as I can tell, the only way get in touch with volunteers is to go one by one, first clicking on "members", then each volunteer's name, then sending them an email through the form. This is cumbersome. And the project leaders don't even have access to their volunteer's email addresses (unless they put it in a second time in "Personal Information", which many are opting not to do). Regardless of what we may have said about this before, we need organizers to have access to email addresses for each of their volunteers (both individually and as a list would be great). I think I remember us saying this would be important because it will get people to use the site, but we were thinking about it wrong. It makes the site less functional overall. As long as organizers are able to recruit a group of volunteers and easily communicate with them, we're doing our job. If not, we're not. Using email outside of the system may not feel ideal, but I think it's just what we need.

**Comment by multilectical** [comment] 2018-01-30 15:15
dupe of #99

**Comment by multilectical** [comment] 2018-09-11 18:28
Under join group for project owners send message to all members.

**Comment by multilectical** [comment] 2018-09-11 18:30
add csv download for volunteers.

**Closed** 2018-09-27 02:56 UTC
Labels: enhancement
